language: python
python: 2.7
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox
script:
    - tox

deploy:
    provider: pypi
    user: tom-mi
    password:
        secure: pektL3VPgW25izjJRUm2b2jR+eAFtVDWFn6+64XaDomy979dMHLcINql4c4Pli7gmCvOiyNjRwVRX5PCPn0kEewFJyV2LMwTkBwWmShaBLgwHb4B8Q2p1/LhYGqh1c1Y7l1PdTechmChHsYdqKdbQ0oiAwYVspwcufD4bh5FDPaw1Mwgz0eCWMDl69DMVldUQfcRpMRIFzwcabW/7/a9Qm22akW4M+cdkFBRSOikK0XqO1ugkLdBaKScfDzl4OHz2S8GpeZMMvDRuEXcruRbcy8/44Iq4zE4m0a6RfFkPG5LmYz2DPjSYikm3a/5K367vhDGqWaC1FS+ZOVVFIVcvYBs6koOeuoQWIgjQSc1ILkIGakRe2a0C468PNHbvflp7MosAg16NcROKQVkQS/Xh0j/ckTSYALUMlo7MeOvl5Df7jsTtG7rDnFLOZSetFDJ0R3J60oQn0Tp1WSJNOjycwqtvwfoECNAp9GBwwmJtURt35PvJ8UTpqA6vFQiL82krX5khF2gnlNxot8QDJGa2hZO1/BiyTQ2MzKAsvQ9bx6MmsUEmDUeipCTpz2uXT298yWEHZypeNvQuTyW4Om53X2GjeNWkqGCHdA2vhqt1kqDMYaJUe2B0HsBIAxIR2XnsOMoBDm5j37D34MH15wVU6LBv1olVMHkBErUvUJmLZY=
    on:
        condition: $TOXENV == py27
        tags: true
        repo: tom-mi/python-mkp
    distributions: bdist_wheel

before_deploy:
    # FIXME: Remove pandoc backport when ci version is sufficient
    - sudo add-apt-repository -y ppa:marutter/c2d4u
    - sudo apt-get update -qq
    - sudo apt-get install -y pandoc
    - pip install pypandoc
